export const REALTIME_CLIENT_METHODS = {
  startTypingChannel: 'StartTypingChannel',
  startTypingConversation: 'StartTypingConversation',
  startConversationCall: 'StartConversationCall',
  acceptConversationCall: 'AcceptConversationCall',
  declineConversationCall: 'DeclineConversationCall',
} as const;

export const REALTIME_SERVER_EVENTS = {
  ready: 'Ready',
  userTyping: 'UserTyping',
  conversationUserTyping: 'ConversationUserTyping',
  messageCreated: 'MessageCreated',
  messageUpdated: 'MessageUpdated',
  messageDeleted: 'MessageDeleted',
  conversationCreated: 'ConversationCreated',
  conversationParticipantLeft: 'ConversationParticipantLeft',
  conversationUpdated: 'ConversationUpdated',
  conversationMessageCreated: 'ConversationMessageCreated',
  conversationMessageUpdated: 'ConversationMessageUpdated',
  conversationMessageDeleted: 'ConversationMessageDeleted',
  conversationCallIncoming: 'ConversationCallIncoming',
  conversationVoiceParticipantJoined: 'ConversationVoiceParticipantJoined',
  conversationVoiceParticipantLeft: 'ConversationVoiceParticipantLeft',
  conversationCallAccepted: 'ConversationCallAccepted',
  conversationCallDeclined: 'ConversationCallDeclined',
  conversationCallEnded: 'ConversationCallEnded',
  voiceParticipantJoined: 'VoiceParticipantJoined',
  voiceParticipantLeft: 'VoiceParticipantLeft',
  guildDeleted: 'GuildDeleted',
  guildOwnershipTransferred: 'GuildOwnershipTransferred',
  guildUpdated: 'GuildUpdated',
  channelCreated: 'ChannelCreated',
  channelUpdated: 'ChannelUpdated',
  channelDeleted: 'ChannelDeleted',
  channelsReordered: 'ChannelsReordered',
  memberJoined: 'MemberJoined',
  memberLeft: 'MemberLeft',
  memberBanned: 'MemberBanned',
  youWereBanned: 'YouWereBanned',
  memberRemoved: 'MemberRemoved',
  youWereKicked: 'YouWereKicked',
  memberRoleUpdated: 'MemberRoleUpdated',
  userPresenceChanged: 'UserPresenceChanged',
  userProfileUpdated: 'UserProfileUpdated',
  reactionAdded: 'ReactionAdded',
  reactionRemoved: 'ReactionRemoved',
  messagePinned: 'MessagePinned',
  messageUnpinned: 'MessageUnpinned',
  messagePreviewUpdated: 'MessagePreviewUpdated',
} as const;
